### ISSUE TITLE
Atualização de KudoCard 3tech

### ISSUE THREAD

**Issue by arqluizalves** [db1group/kudomundo-frontend#34]
Trocar KudoCard:
Desculpinha de Qualidade - Xulia
por
Bow de Shola - Imagem em anexo

![Bow de Shola](https://user-images.githubusercontent.com/55717634/70465198-30426000-1a9f-11ea-86a2-1895e8df32da.png)

**Comment by ramonnteixeira** [comment]
Feito.

peço que assuntos de whitelabel sejam tratados no projeto [neste repositório](https://github.com/ramonnteixeira/kudomundo-whitelabel/), pois este repositório é público e podemos estar expondo dados sensíveis.
