### ISSUE TITLE
Any - Atualização KudoCards

### ISSUE THREAD

**Issue by arqluizalves** [db1group/kudomundo-frontend#35]
Deixar apenas 8 Kudocards disponíveis no Kudomundo do Anymarket.

Eis os escolhidos para serem mantidos:

1. Qualidade Garantida;
2. Foi Lá e Resolveu;
3. Mano, Que Massa;
4. Vale Chopp!;
5. Vale Litrão!;
6. Vale Tequila!;
7. Arrasou!
8. Meu Herói

Remover os outros existentes.

![image](https://user-images.githubusercontent.com/55717634/70664119-8bfc1d00-1c48-11ea-8f62-2f78271dc3cf.png)

**Comment by ramonnteixeira** [comment]
publicado
