### ISSUE TITLE
3Tech - Incluir Membros

### ISSUE THREAD

**Issue by luizalvesfilho** [db1group/kudomundo-frontend#36]
incluir no KudoMundo da 3tech os colaboradores:
- altieres.matos@db1.com.br 
- juliano.bailao@db1.com.br

**Comment by ramonnteixeira** [comment]
Feito.

peço que assuntos de whitelabel sejam tratados no projeto [neste repositório](https://github.com/ramonnteixeira/kudomundo-whitelabel/), pois este repositório é público e podemos estar expondo dados sensíveis.
